version: '3'
services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-products
    volumes:
      - dbbase:/var/lib/mysql
    environment:
      MYSQL_DATABASE: products
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

volumes:
  dbbase:
