version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: productsJson
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: minha_database
      MYSQL_USER: mysqldummy
      MYSQL_PASSWORD: sqldummy
    ports:
      - "3306:3306"
